version: 2.1

orbs:
  python: circleci/python@2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          args: pytest
      - run:
          name: Run Test
          command: |
            pip install requests
            pytest --junitxml=test-results/junit.xml Testgetapi.py
      - store_test_results:
          path: test-results
workflows:
  HW4:
    jobs:
      - build-and-test